# Generated by Django 2.0.2 on 2018-03-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bookmarkedcarpark_carpark_recordedparkinglot_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpark',
            name='carParkAddress',
        ),
        migrations.RemoveField(
            model_name='carpark',
            name='carParkCapacity',
        ),
        migrations.AddField(
            model_name='carpark',
            name='satRate',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpark',
            name='sunRate',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpark',
            name='weekDaysRate1',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpark',
            name='weekDaysRate2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
