# Generated by Django 2.0.2 on 2018-03-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180306_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpark',
            name='carParkType',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpark',
            name='freeParking',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpark',
            name='nightParking',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpark',
            name='parkingSystem',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpark',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
