# Generated by Django 2.0.2 on 2018-03-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_bookmarkedcarpark_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedparkinglot',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
