# Generated by Django 2.0.2 on 2018-03-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180326_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpark',
            name='x',
        ),
        migrations.RemoveField(
            model_name='carpark',
            name='y',
        ),
    ]
