# Generated by Django 2.0.2 on 2018-04-03 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180326_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarParkPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsthour', models.FloatField()),
                ('subhalfhour', models.FloatField()),
                ('perentry', models.FloatField()),
                ('carPark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CarPark')),
            ],
        ),
    ]
