# Generated by Django 2.0.2 on 2018-04-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_carparkprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='carparkprice',
            name='freeperiod',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='carparkprice',
            name='subfifteen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='carparkprice',
            name='subhour',
            field=models.FloatField(default=0),
        ),
    ]
